### ISSUE TITLE
DF - Investigate about Database

### ISSUE THREAD

**Issue by luanparedes** [luanparedes/DarknessFalls#11]
Investigate about:
This investigation is about which database we're gonna use in our game.
Search about default by Unity.

Investigation references:
-Local Settings
-Sqlite
-MongoDB

**Comment by YuDarvish** [comment]
To read:

https://stackoverflow.com/questions/34426570/best-way-to-save-data-in-unity-game
https://blog.unity.com/games/persistent-data-how-to-save-your-game-states-and-settings

**Comment by luanparedes** [comment]
The first time that app is open, it creates the player, but for now, it is creating everytime that opens the app. So it needs to remove from database the player created before.
